<a href="https://colab.research.google.com/github/Do-Nhat-Truong/AI-VietNam-Module4-week4/blob/main/M4Week4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import numpy as np

In [36]:


class CustomLinearRegression:
    def __init__(self, X_data, y_target, learning_rate=0.01, num_epochs=10000):
        self.num_samples = X_data.shape[0]
        self.X_data = np.c_[np.ones((self.num_samples, 1)), X_data]
        self.y_target = y_target
        self.learning_rate = learning_rate
        self.num_epochs = num_epochs

        # Khởi tạo trọng số ngẫu nhiên
        self.theta = np.random.randn(self.X_data.shape[1], 1)
        self.losses = []

    def compute_loss(self, y_pred, y_target):
        # Giả sử bạn muốn tính toán hàm mất mát theo công thức lỗi bình phương trung bình (MSE)
        loss = np.mean((y_pred - y_target) ** 2)
        return loss

    def predict(self, X_data):
        # Dự đoán dựa trên X_data và trọng số theta
        y_pred = X_data.dot(self.theta)
        return y_pred

    def fit(self):
        for epoch in range(self.num_epochs):
            # Dự đoán giá trị y_pred
            y_pred = self.predict(self.X_data)

            # Tính toán hàm mất mát và thêm vào danh sách losses
            loss = self.compute_loss(y_pred, self.y_target)
            self.losses.append(loss)

            # Tính gradient
            gradients = 2 * self.X_data.T.dot(y_pred - self.y_target) / self.num_samples

            # Cập nhật trọng số
            self.theta -= self.learning_rate * gradients

            if (epoch % 50) == 0:
                print(f'Epoch: {epoch} - Loss: {loss}')

        return {
            'loss': sum(self.losses) / len(self.losses),
            'weight': self.theta
        }


In [37]:
def r2score(y_pred, y):
    rss = np.sum((y_pred - y) ** 2)
    tss = np.sum((y - y.mean()) ** 2)
    r2 = 1 - (rss / tss)
    return r2

In [38]:
# Case 1
y_pred = np.array ([1 , 2 , 3 , 4 , 5])
y = np.array ([1 , 2 , 3 , 4 , 5])
r1=r2score(y_pred , y )

# Case 2
y_pred = np.array([1 , 2 , 3 , 4 , 5])
y = np.array([3 , 5 , 5 , 2 , 4])
r2=r2score(y_pred , y )

print(r1,r2)

1.0 -2.235294117647059


In [39]:
def create_polynomial_features (X , degree =2):
  X_new = X
  for d in range(2, degree + 1):
    X_new = np.c_[X_new, np.power(X, d)]
  return X_new
X = np.array ([[1] , [2] , [3]])
print(create_polynomial_features(X, degree = 2))

[[1 1]
 [2 4]
 [3 9]]


In [40]:
def create_polynomial_features2(X, degree=2):
    """ Creates the polynomial features """
    X_mem = []
    for X_sub in X.T:
        X_new = X_sub
        for d in range(2, degree + 1):
            X_new = np.c_[X_new, np.power(X_sub, d)]
        X_mem.extend(X_new.T)
    return np.c_[X_mem].T
# Kiểm tra mã
X = np.array([
    [1, 2],
    [2, 3],
    [3, 4]
])
degree = 2
X_poly = create_polynomial_features2(X, degree)
print(X_poly)

[[ 1  1  2  4]
 [ 2  4  3  9]
 [ 3  9  4 16]]


In [55]:
!gdown 1A8kK0IEsT3w8htzU18ihFr5UV-euhquC


Downloading...
From: https://drive.google.com/uc?id=1A8kK0IEsT3w8htzU18ihFr5UV-euhquC
To: /content/SalesPrediction.csv
100% 206k/206k [00:00<00:00, 78.7MB/s]


In [56]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn . preprocessing import StandardScaler
# Tải dữ liệu từ file SalesPrediction.csv
df = pd.read_csv('SalesPrediction.csv')
#df


In [57]:
# Thực hiện One Hot Encoding cho cột Influencer
df = pd.get_dummies(df, columns=['Influencer'])
# Xem dữ liệu sau khi mã hóa
print(df.head())

     TV      Radio  Social Media       Sales  Influencer_Macro  \
0  16.0   6.566231      2.907983   54.732757             False   
1  13.0   9.237765      2.409567   46.677897             False   
2  41.0  15.886446      2.913410  150.177829             False   
3  83.0  30.020028      6.922304  298.246340             False   
4  15.0   8.437408      1.405998   56.594181             False   

   Influencer_Mega  Influencer_Micro  Influencer_Nano  
0             True             False            False  
1             True             False            False  
2             True             False            False  
3             True             False            False  
4            False              True            False  


In [58]:
# Xử lý các giá trị Null
df = df.fillna(df.mean())

# Lấy các đặc trưng (features)
X = df[['TV', 'Radio', 'Social Media', 'Influencer_Macro', 'Influencer_Mega',
        'Influencer_Micro', 'Influencer_Nano']]
y = df[['Sales']]

In [59]:
# Chia tập dữ liệu thành tập train và test

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.33,
    random_state=0
)

#print(X_train,y_train,X_test,y_test)

In [73]:
from sklearn . preprocessing import StandardScaler
scaler = StandardScaler()

X_train_processed = scaler.fit_transform(X_train )
X_test_processed = scaler.fit_transform(X_test )

#print(np.mean(X_train))
scaler.mean_[0]

53.850231941683234

In [65]:
from sklearn . preprocessing import PolynomialFeatures
poly_features = PolynomialFeatures ( degree =2)
X_train_poly = poly_features . fit_transform (X_train_processed )

X_test_poly = poly_features . transform ( X_test_processed )
#print(X_train_poly,X_test_poly)

[[ 1.          0.33869282 -0.3935435  ...  2.99869452 -1.00174084
   0.33464052]
 [ 1.         -0.19852366 -0.28899849 ...  0.33347845  0.33405898
   0.33464052]
 [ 1.         -0.42875929 -1.07436552 ...  0.33347845 -0.99826219
   2.98828125]
 ...
 [ 1.         -1.61831007 -1.72922605 ...  0.33347845 -0.99826219
   2.98828125]
 [ 1.         -0.58224971 -0.91383556 ...  2.99869452 -1.00174084
   0.33464052]
 [ 1.         -1.27295662 -1.45779228 ...  2.99869452 -1.00174084
   0.33464052]] [[ 1.         -0.33831381 -0.09176884 ...  2.89922481 -0.97220258
   0.32601054]
 [ 1.          0.77025605  1.17821405 ...  0.34491979 -1.02859221
   3.06738544]
 [ 1.          1.15252152  1.04864751 ...  0.34491979  0.33533191
   0.32601054]
 ...
 [ 1.          0.96138879  1.12388703 ...  0.34491979  0.33533191
   0.32601054]
 [ 1.         -0.4147669  -0.29991669 ...  0.34491979  0.33533191
   0.32601054]
 [ 1.         -0.91171201 -1.21956787 ...  0.34491979  0.33533191
   0.32601054]]


In [66]:
from sklearn . linear_model import LinearRegression
from sklearn . metrics import r2_score
poly_model = LinearRegression ()
poly_model . fit ( X_train_poly , y_train )
preds = poly_model . predict ( X_test_poly )
r2_score ( y_test , preds )

-2.2119776223197106e+21